swagger: "2.0"
info:
  version: 0.0.0
  title: ruo api example
host: localhost:8080
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: example
